CREATE TABLE estados (
	codigo NUMBER GENERATED by default on null as IDENTITY,
    nome   VARCHAR2(20),
    
    CONSTRAINT pk_codigo_estado PRIMARY KEY(codigo)
);

CREATE TABLE cidade (
	codigo NUMBER GENERATED by default on null as IDENTITY,
    nome   VARCHAR2(40),
    estado NUMBER,
    
    CONSTRAINT pk_codigo_cidade PRIMARY KEY (codigo),
    CONSTRAINT fk_codigo_estado FOREIGN KEY (estado) REFERENCES estados (codigo)
);

CREATE TABLE centro_distribuicao (
	codigo NUMBER GENERATED by default on null as IDENTITY,
    nome   VARCHAR2(20),
    cidade NUMBER,
	bairro VARCHAR2(40),
	logradouro VARCHAR2(50),
    
    CONSTRAINT pk_codigo_centro_distribuicao PRIMARY KEY (codigo),
    CONSTRAINT fk_codigo_cidade FOREIGN KEY (cidade) REFERENCES cidade (codigo)
);


