CREATE TABLE professores (
	codigo NUMBER GENERATED by default on null as IDENTITY,
    nome   VARCHAR2(20) NOT NULL,
    
    CONSTRAINT pk_codigo_professor PRIMARY KEY(codigo)
);

CREATE TABLE materias (
	codigo    NUMBER GENERATED by default on null as IDENTITY,
    professor NUMBER,
    nome      VARCHAR2(20),
    
    CONSTRAINT pk_codigo_materia PRIMARY KEY (codigo)
);

CREATE TABLE turmas (
	codigo NUMBER GENERATED by default on null as IDENTITY,
    nome   VARCHAR2(2),
    turno  VARCHAR2(10),
    
    CONSTRAINT pk_codigo_turma PRIMARY KEY (codigo)
);

CREATE TABLE alunos (
	codigo NUMBER GENERATED by default on null as IDENTITY,
    nome   VARCHAR2(30),
    
    CONSTRAINT pk_codigo_aluno PRIMARY KEY(codigo)
);

CREATE TABLE alunos_turmas (
    codigo_aluno NUMBER,
    codigo_materia NUMBER,
    codigo_turma NUMBER,
    
    CONSTRAINT fk_codigo_aluno FOREIGN KEY (codigo_aluno) REFERENCES alunos (codigo),
    CONSTRAINT fk_codigo_materia FOREIGN KEY (codigo_materia) REFERENCES materias (codigo),
    CONSTRAINT fk_codigo_turma FOREIGN KEY (codigo_turma) REFERENCES turmas (codigo)
);


INSERT INTO professores (nome) VALUES ('Renato');
INSERT INTO professores (nome) VALUES ('Oscar');
INSERT INTO professores (nome) VALUES ('Cátia');
INSERT INTO professores (nome) VALUES ('Osvaldo');
INSERT INTO professores (nome) VALUES ('Marília');
INSERT INTO professores (nome) VALUES ('Paula');
INSERT INTO professores (nome) VALUES ('Otávio');
INSERT INTO professores (nome) VALUES ('Airton');
SELECT * FROM professores;


INSERT INTO materias (professor, nome) VALUES (1, 'Matemática');
INSERT INTO materias (professor, nome) VALUES (2, 'Geografia');
INSERT INTO materias (professor, nome) VALUES (7, 'Química');
INSERT INTO materias (professor, nome) VALUES (6, 'Filosofia');
INSERT INTO materias (professor, nome) VALUES (1, 'Física');
INSERT INTO materias (professor, nome) VALUES (3, 'Português');
INSERT INTO materias (professor, nome) VALUES (3, 'Inglês');
INSERT INTO materias (professor, nome) VALUES (6, 'Sociologia');
INSERT INTO materias (professor, nome) VALUES (5, 'Português');
INSERT INTO materias (professor, nome) VALUES (4, 'História');
INSERT INTO materias (professor, nome) VALUES (4, 'Sociologia');
INSERT INTO materias (professor, nome) VALUES (5, 'Espanhol');
INSERT INTO materias (professor, nome) VALUES (8, 'Biologia');
INSERT INTO materias (professor, nome) VALUES (8, 'Química');
SELECT * FROM materias;


INSERT INTO turmas (nome, turno) VALUES ('6A', 'Matutino');
INSERT INTO turmas (nome, turno) VALUES ('6B', 'Vespertino');
INSERT INTO turmas (nome, turno) VALUES ('7A', 'Matutino');
INSERT INTO turmas (nome, turno) VALUES ('7B', 'Vespertino');
INSERT INTO turmas (nome, turno) VALUES ('8A', 'Matutino');
INSERT INTO turmas (nome, turno) VALUES ('8B', 'Vespertino');
SELECT * FROM turmas;


INSERT INTO alunos (nome) VALUES ('Alessandra');
INSERT INTO alunos (nome) VALUES ('Emanuela');
INSERT INTO alunos (nome) VALUES ('Cíntia');
INSERT INTO alunos (nome) VALUES ('Diego');
INSERT INTO alunos (nome) VALUES ('Eduardo');
INSERT INTO alunos (nome) VALUES ('Larissa');
INSERT INTO alunos (nome) VALUES ('Jonathan');
INSERT INTO alunos (nome) VALUES ('Cleber');
INSERT INTO alunos (nome) VALUES ('Jéssica');
INSERT INTO alunos (nome) VALUES ('Lucas');
INSERT INTO alunos (nome) VALUES ('Murilo');
INSERT INTO alunos (nome) VALUES ('Marcelo');
INSERT INTO alunos (nome) VALUES ('Rebeca');
INSERT INTO alunos (nome) VALUES ('Tatiana');
INSERT INTO alunos (nome) VALUES ('Taís');
INSERT INTO alunos (nome) VALUES ('Gabriel');
INSERT INTO alunos (nome) VALUES ('Felipe');
INSERT INTO alunos (nome) VALUES ('Eliza');
INSERT INTO alunos (nome) VALUES ('Sarah');
INSERT INTO alunos (nome) VALUES ('Patrícia');
SELECT * FROM alunos;


INSERT INTO alunos_turmas VALUES (1, 1, 1);
INSERT INTO alunos_turmas VALUES (2, 5, 1);
INSERT INTO alunos_turmas VALUES (3, 10, 2);
INSERT INTO alunos_turmas VALUES (4, 14, 1);
INSERT INTO alunos_turmas VALUES (5, 1, 1);
INSERT INTO alunos_turmas VALUES (6, 2, 6);
INSERT INTO alunos_turmas VALUES (7, 3, 2);
INSERT INTO alunos_turmas VALUES (8, 6, 3);
INSERT INTO alunos_turmas VALUES (9, 5, 4);
INSERT INTO alunos_turmas VALUES (10, 4, 4);
INSERT INTO alunos_turmas VALUES (11, 1, 5);
INSERT INTO alunos_turmas VALUES (12, 5, 2);
INSERT INTO alunos_turmas VALUES (13, 8, 3);
INSERT INTO alunos_turmas VALUES (14, 13, 6);
INSERT INTO alunos_turmas VALUES (15, 6, 5);
INSERT INTO alunos_turmas VALUES (16, 14, 3);
INSERT INTO alunos_turmas VALUES (17, 9, 5);
INSERT INTO alunos_turmas VALUES (18, 3, 1);
INSERT INTO alunos_turmas VALUES (19, 8, 4);
INSERT INTO alunos_turmas VALUES (20, 5, 6);
INSERT INTO alunos_turmas VALUES (4, 10, 3);
INSERT INTO alunos_turmas VALUES (15, 2, 1);
INSERT INTO alunos_turmas VALUES (12 ,10, 1);
INSERT INTO alunos_turmas VALUES (9, 8, 6);
SELECT * FROM alunos_turmas;


SELECT 
    alunos.nome,
    materias.nome,
    turmas.nome
FROM alunos_turmas 
INNER JOIN alunos ON (alunos.codigo = alunos_turmas.codigo_aluno)
INNER JOIN materias ON (materias.codigo = alunos_turmas.codigo_materia)
INNER JOIN turmas ON (turmas.codigo = alunos_turmas.codigo_turma);


SELECT 
    professores.nome,
    materias.nome
FROM materias INNER JOIN professores ON (materias.professor = professores.codigo);


SELECT 
    COUNT(*) as Quantidade_de_alunos,
    turmas.nome
FROM alunos_turmas
INNER JOIN turmas ON (turmas.codigo = alunos_turmas.codigo_turma)
GROUP BY turmas.nome;


SELECT 
    COUNT(*) as Quantidade_de_alunos,
    turmas.turno
FROM alunos_turmas
INNER JOIN turmas ON (turmas.codigo = alunos_turmas.codigo_turma)
GROUP BY turmas.turno;


SELECT 
	alunos.nome AS Aluno,
    turmas.nome AS Turma,
    materias.nome AS Matéria
FROM alunos_turmas 
INNER JOIN alunos ON (alunos.codigo = alunos_turmas.codigo_aluno)
INNER JOIN turmas ON (turmas.codigo = alunos_turmas.codigo_turma)
INNER JOIN materias ON (materias.codigo = alunos_turmas.codigo_materia)
INNER JOIN professores ON (professores.codigo = materias.professor)
WHERE professores.nome = 'Renato';


SELECT
	professores.nome
FROM professores
INNER JOIN materias ON materias.nome = 'Química' AND materias.professor = professores.codigo;


SELECT
	alunos.nome
FROM alunos_turmas 
INNER JOIN alunos ON (alunos.codigo = alunos_turmas.codigo_aluno)
INNER JOIN materias ON (materias.codigo = alunos_turmas.codigo_materia)
WHERE materias.nome = 'História';


SELECT 
	professores.nome as Professor
FROM professores
INNER JOIN materias ON (materias.professor = professores.codigo)
WHERE materias.nome IN ('Português', 'Inglês') 
GROUP BY professores.nome HAVING COUNT(*) > 1;


SELECT 
	COUNT(*),
    materias.nome as Matéria
FROM alunos_turmas 
INNER JOIN alunos ON (alunos.codigo = alunos_turmas.codigo_aluno)
INNER JOIN materias ON (materias.codigo = alunos_turmas.codigo_materia)
GROUP BY materias.nome;


SELECT
	alunos.nome,
	materias.nome
FROM alunos_turmas
INNER JOIN alunos ON (alunos.codigo = alunos_turmas.codigo_aluno) 
INNER JOIN materias ON (materias.codigo = alunos_turmas.codigo_materia)
INNER JOIN professores ON (materias.professor = professores.codigo)
WHERE professores.nome = 'Cátia' AND materias.nome = 'Inglês';


SELECT 
	COUNT(*) AS Quantidade_de_alunos
FROM alunos_turmas
INNER JOIN alunos ON (alunos.codigo = alunos_turmas.codigo_aluno)
INNER JOIN materias ON (materias.codigo = alunos_turmas.codigo_materia)
INNER JOIN professores ON (professores.codigo = materias.professor)
INNER JOIN turmas ON (turmas.codigo = alunos_turmas.codigo_turma)
WHERE turmas.nome = '6A' AND materias.nome = 'Matemática' AND professores.nome = 'Renato';


SELECT 
	materias.nome
FROM materias
INNER JOIN professores ON (professores.codigo = materias.professor)
WHERE professores.nome = 'Airton';


SELECT 
	COUNT(*) AS Quantdade_de_alunos
FROM alunos_turmas
INNER JOIN alunos ON (alunos.codigo = alunos_turmas.codigo_aluno)
INNER JOIN turmas ON (turmas.codigo = alunos_turmas.codigo_turma)
INNER JOIN materias ON (materias.codigo = alunos_turmas.codigo_materia)
WHERE turmas.turno = 'Vespertino' AND materias.nome = 'Biologia';


--DROP TABLE alunos_turmas;
--DROP TABLE alunos;
--DROP TABLE professores;
--DROP TABLE materias;
--DROP TABLE turmas;
