CREATE TABLE cargos (
       codigo  NUMBER GENERATED by default on null as IDENTITY,
       nome    VARCHAR2(40),
       salario NUMBER,
       
       CONSTRAINT pk_codigo_cargos PRIMARY KEY (codigo)
);

CREATE TABLE colaboradores (
       codigo     NUMBER GENERATED by default on null as IDENTITY,
       nome       VARCHAR2(40),
       nascimento DATE,
       cargo      NUMBER,
       estado     VARCHAR2(2),
       cidade     VARCHAR2(20),
       genero     VARCHAR2(10),
       
       CONSTRAINT pk_codigo_colaboradores PRIMARY KEY (codigo),
       CONSTRAINT fk_codigo_cargos FOREIGN KEY (cargo) REFERENCES cargos (codigo)
);
TRUNCATE TABLE colaboradores;
TRUNCATE TABLE cargos;

INSERT INTO cargos (nome, salario) VALUES ('Desenvolvedor', 3000);
INSERT INTO cargos (nome, salario) VALUES ('Analista', 4500);
INSERT INTO cargos (nome, salario) VALUES ('Arquiteto de Software', 6200);
INSERT INTO cargos (nome, salario) VALUES ('Administrador de Banco de Dados', 7700);
INSERT INTO cargos (nome, salario) VALUES ('Gerente de Projetos', 9000);


INSERT INTO colaboradores (nome, nascimento, cargo, estado, cidade, genero) VALUES ('Jefferson', TO_DATE('1973/05/19', 'yyyy/mm/dd'), 1, 'SC', 'Blumenau', 'Masculino');
INSERT INTO colaboradores (nome, nascimento, cargo, estado, cidade, genero) VALUES ('Larissa', TO_DATE('1991/01/22', 'yyyy/mm/dd'), 5, 'SC', 'Joinville', 'Feminino');
INSERT INTO colaboradores (nome, nascimento, cargo, estado, cidade, genero) VALUES ('Cleber', TO_DATE('1987/03/18', 'yyyy/mm/dd'), 2, 'PR', 'Curitiba', 'Masculino');
INSERT INTO colaboradores (nome, nascimento, cargo, estado, cidade, genero) VALUES ('Luciano', TO_DATE('1995/08/09', 'yyyy/mm/dd'), 1, 'SC', 'Blumenau', 'Masculino');
INSERT INTO colaboradores (nome, nascimento, cargo, estado, cidade, genero) VALUES ('J�ssica', TO_DATE('1988/08/22', 'yyyy/mm/dd'), 4, 'SC', 'Florian�polis', 'Feminino');
INSERT INTO colaboradores (nome, nascimento, cargo, estado, cidade, genero) VALUES ('Guilherme', TO_DATE('1982/11/16', 'yyyy/mm/dd'), 2, 'SC', 'Blumenau', 'Masculino');
INSERT INTO colaboradores (nome, nascimento, cargo, estado, cidade, genero) VALUES ('Marcelo', TO_DATE('1993/04/15', 'yyyy/mm/dd'), 2, 'PR', 'Londrina', 'Masculino');
INSERT INTO colaboradores (nome, nascimento, cargo, estado, cidade, genero) VALUES ('Brenda', TO_DATE('1992/02/17', 'yyyy/mm/dd'), 1, 'SC', 'Joinville', 'Feminino');
INSERT INTO colaboradores (nome, nascimento, cargo, estado, cidade, genero) VALUES ('Rebeca', TO_DATE('1984/06/26', 'yyyy/mm/dd'), 4, 'SC', 'Blumenau', 'Feminino');
INSERT INTO colaboradores (nome, nascimento, cargo, estado, cidade, genero) VALUES ('Cristiano', TO_DATE('1983/07/02', 'yyyy/mm/dd'), 1, 'SC', 'Florian�polis', 'Masculino');
INSERT INTO colaboradores (nome, nascimento, cargo, estado, cidade, genero) VALUES ('�der', TO_DATE('1991/11/10', 'yyyy/mm/dd'), 1, 'SC', 'Blumenau', 'Masculino');
INSERT INTO colaboradores (nome, nascimento, cargo, estado, cidade, genero) VALUES ('William', TO_DATE('1992/12/17', 'yyyy/mm/dd'), 2, 'PR', 'Curitiba', 'Masculino');
INSERT INTO colaboradores (nome, nascimento, cargo, estado, cidade, genero) VALUES ('Vanessa', TO_DATE('1996/09/29', 'yyyy/mm/dd'), 1, 'SC', 'Blumenau', 'Feminino');
INSERT INTO colaboradores (nome, nascimento, cargo, estado, cidade, genero) VALUES ('Robson', TO_DATE('1984/05/30', 'yyyy/mm/dd'), 1, 'PR', 'Londrina', 'Masculino');
INSERT INTO colaboradores (nome, nascimento, cargo, estado, cidade, genero) VALUES ('Tatiana', TO_DATE('1990/02/03', 'yyyy/mm/dd'), 5, 'PR', 'Curitiba', 'Feminino');
INSERT INTO colaboradores (nome, nascimento, cargo, estado, cidade, genero) VALUES ('Henrique', TO_DATE('1999/10/07', 'yyyy/mm/dd'), 1, 'SC', 'Blumenau', 'Masculino');
INSERT INTO colaboradores (nome, nascimento, cargo, estado, cidade, genero) VALUES ('Lorena', TO_DATE('1996/04/20', 'yyyy/mm/dd'), 1, 'SC', 'Joinville', 'Feminino');
INSERT INTO colaboradores (nome, nascimento, cargo, estado, cidade, genero) VALUES ('Carla', TO_DATE('1988/09/28', 'yyyy/mm/dd'), 4, 'PR', 'Curitiba', 'Feminino');
INSERT INTO colaboradores (nome, nascimento, cargo, estado, cidade, genero) VALUES ('Alexandre', TO_DATE('1982/07/17', 'yyyy/mm/dd'), 2, 'SC', 'Blumenau', 'Masculino');

SELECT * FROM colaboradores;


SELECT 
       colaboradores.nome as Nome_do_colaborador, 
       cargos.nome as Nome_do_cargo, 
       cargos.salario as Salário 
FROM colaboradores INNER JOIN cargos ON (colaboradores.cargo = cargos.codigo);


SELECT 
     COUNT(colaboradores.nome) as Nomes,
     cargos.nome as Cargo
FROM colaboradores RIGHT JOIN cargos ON (colaboradores.cargo = cargos.codigo) GROUP BY cargos.nome;


SELECT
     nome,
     idade  
FROM (
     SELECT 
           nome, 
           ((EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM nascimento))) as idade 
           FROM colaboradores
) WHERE idade BETWEEN 20 AND 30;


SELECT COUNT(*), estado FROM colaboradores GROUP BY estado;


SELECT COUNT(*), cidade FROM colaboradores GROUP BY cidade;


SELECT
     COUNT(*) as Quantidade
FROM (
     SELECT  
           genero,
           estado,
           ((EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM nascimento))) as idade 
           FROM colaboradores)
WHERE idade >= 30 AND genero = 'Feminino' AND estado = 'PR';


SELECT AVG(salario) as Media_Dos_Salarios FROM cargos;


SELECT * FROM (
       SELECT 
         colaboradores.nome,
         ((EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM nascimento))) as idade,
         cargos.nome AS cargo,
         colaboradores.estado,
         colaboradores.cidade,
         colaboradores.genero
       FROM colaboradores INNER JOIN cargos 
       ON(colaboradores.cargo = cargos.codigo) 
       ORDER BY idade DESC
) WHERE ROWNUM = 1;


SELECT * FROM colaboradores WHERE EXTRACT(YEAR FROM nascimento) < 2000;


DROP TABLE colaboradores;
DROP TABLE cargos;
