CREATE TABLE viagens (
       codigo NUMBER GENERATED by default on null as IDENTITY,
       ida VARCHAR2(20),
       volta VARCHAR2(20),
       data_ida DATE,
       data_volta DATE,
            
       CONSTRAINT pk_codigo PRIMARY KEY(codigo)
);

TRUNCATE TABLE viagens;
INSERT INTO viagens (ida, volta, data_ida, data_volta) VALUES ('S�o Paulo', 'Londres', TO_DATE('12/06/2022 09:30', 'dd/mm/yyyy hh24:mi'), TO_DATE('21/06/2022 17:00', 'dd/mm/yyyy hh24:mi'));
INSERT INTO viagens (ida, volta, data_ida, data_volta) VALUES ('Nova Iorque', 'Berlim', TO_DATE('21/07/2022 10:45', 'dd/mm/yyyy hh24:mi'), TO_DATE('03/08/2022 11:00', 'dd/mm/yyyy hh24:mi'));
INSERT INTO viagens (ida, volta, data_ida, data_volta) VALUES ('Rio de Janeiros', 'Buenos Aires', TO_DATE('19/08/2022 11:00', 'dd/mm/yyyy hh24:mi'), TO_DATE('01/09/2022 12:00', 'dd/mm/yyyy hh24:mi'));
INSERT INTO viagens (ida, volta, data_ida, data_volta) VALUES ('Manaus', 'Cidade do M�xico', TO_DATE('07/10/2022 15:00', 'dd/mm/yyyy hh24:mi'), TO_DATE('31/10/2022 06:00', 'dd/mm/yyyy hh24:mi') );
INSERT INTO viagens (ida, volta, data_ida, data_volta) VALUES ('S�o Paulo', 'Lisboa', TO_DATE('06/07/2022 10:45', 'dd/mm/yyyy hh24:mi'), TO_DATE('10/08/2022 14:00', 'dd/mm/yyyy hh24:mi'));
INSERT INTO viagens (ida, volta, data_ida, data_volta) VALUES ('Bras�lia', 'S�o Paulo', TO_DATE('12/1/2022 8:30', 'dd/mm/yyyy hh24:mi'), TO_DATE('19/11/2022 15:50', 'dd/mm/yyyy hh24:mi'));
INSERT INTO viagens (ida, volta, data_ida, data_volta) VALUES ('Belo Horizonte', 'Bogot�', TO_DATE('07/09/2022 17:00', 'dd/mm/yyyy hh24:mi'), TO_DATE('21/09/2022 6:30', 'dd/mm/yyyy hh24:mi'));
INSERT INTO viagens (ida, volta, data_ida, data_volta) VALUES ('S�o Paulo', 'Belo Horizonte', TO_DATE('06/07/2022 10:00', 'dd/mm/yyyy hh24:mi'), TO_DATE('10/07/2022 16:30', 'dd/mm/yyyy hh24:mi'));
INSERT INTO viagens (ida, volta, data_ida, data_volta) VALUES ('Belo Horizonte', 'Porto Alegre', TO_DATE('20/08/2022 7:30', 'dd/mm/yyyy hh24:mi'), TO_DATE('25/08/2022 14:00', 'dd/mm/yyyy hh24:mi'));
INSERT INTO viagens (ida, volta, data_ida, data_volta) VALUES ('Joinville', 'Porto Alegre', TO_DATE('29/06/2022 8:30', 'dd/mm/yyyy hh24:mi'), TO_DATE('05/07/2022 18:00', 'dd/mm/yyyy hh24:mi'));
INSERT INTO viagens (ida, volta, data_ida, data_volta) VALUES ('Rio de Janeiro', 'Dubai', TO_DATE('20/07/2022 8:50', 'dd/mm/yyyy hh24:mi'), TO_DATE('15/08/2022 6:00', 'dd/mm/yyyy hh24:mi'));
INSERT INTO viagens (ida, volta, data_ida, data_volta) VALUES ('S�o Paulo', 'Manaus', TO_DATE('17/07/2022 7:00', 'dd/mm/yyyy hh24:mi'), TO_DATE('23/07/2022 20:30', 'dd/mm/yyyy hh24:mi'));

SELECT * FROM viagens;


SELECT DISTINCT(ida), COUNT(*) FROM viagens GROUP BY ida;


SELECT 
       COUNT(turno),
       turno
FROM (
     SELECT 
       (CASE
            WHEN TO_CHAR(data_ida,'HH24') <= 12 THEN 'Matutino'
            WHEN TO_CHAR(data_ida,'HH24') <= 18 THEN 'Vespertino'
            WHEN TO_CHAR(data_ida,'HH24') <= 23 THEN 'Noturno'
       END) as turno FROM viagens
) GROUP BY turno;


SELECT
  ida, 
  volta
FROM viagens WHERE ( EXTRACT(MONTH FROM data_volta) = 7);


SELECT * FROM viagens WHERE (ida = 'Dubai') OR (volta = 'Dubai'); 


SELECT * FROM viagens WHERE (TO_CHAR(data_ida, 'HH24') BETWEEN 0 AND 12) AND EXTRACT(MONTH FROM data_ida) = 7;


SELECT
     MAX(ida) as Cidade,
     COUNT(*) as Quantidade
FROM viagens WHERE ida = (SELECT MAX(ida) FROM viagens);


SELECT * FROM (SELECT volta, COUNT(volta) FROM viagens GROUP BY volta ORDER BY COUNT(volta) DESC) WHERE ROWNUM = 1;


SELECT * FROM viagens ORDER BY data_ida;

DROP TABLE viagens;
