DROP TABLE produtos;
DROP TABLE marcas;

CREATE TABLE marcas (
	codigo NUMBER GENERATED by default on null as IDENTITY,
	nome   VARCHAR2(20),

	CONSTRAINT pk_codigo_marca PRIMARY KEY(codigo)
);

CREATE TABLE produtos (
	codigo  NUMBER GENERATED by default on null as IDENTITY,
	nome    VARCHAR2(40),
	valor   NUMBER,
	estoque NUMBER,
	marca   NUMBER,

	CONSTRAINT pk_codigo_produto PRIMARY KEY (codigo),
	CONSTRAINT fk_codigo_marca   FOREIGN KEY (marca) REFERENCES marcas (codigo)
);

INSERT INTO marcas (nome) VALUES ('Nike');
INSERT INTO marcas (nome) VALUES ('Adidas');
INSERT INTO marcas (nome) VALUES ('Colcci');
INSERT INTO marcas (nome) VALUES ('Tommy Hilfiger');
INSERT INTO marcas (nome) VALUES ('Hering');
INSERT INTO marcas (nome) VALUES ('Vans');
INSERT INTO marcas (nome) VALUES ('Vizzano');
INSERT INTO marcas (nome) VALUES ('Aramis');
INSERT INTO marcas (nome) VALUES ('Reserva');
SELECT * FROM marcas;

INSERT INTO produtos (nome, valor, estoque, marca) VALUES ('Tênis Adidas Performance',  345.00, 765, 2);
INSERT INTO produtos (nome, valor, estoque, marca) VALUES ('Tênis Nike Revolution',  769.00, 1235, 1);
INSERT INTO produtos (nome, valor, estoque, marca) VALUES ('Blusa feminina rosa',  99.00, 754, 6);
INSERT INTO produtos (nome, valor, estoque, marca) VALUES ('Camisa social branca',  180.99, 235, 8);
INSERT INTO produtos (nome, valor, estoque, marca) VALUES ('Bota Chelsea Lacey',  322.00, 98, 3);
INSERT INTO produtos (nome, valor, estoque, marca) VALUES ('Blusa moletom Romance',  150.76, 324, 3);
INSERT INTO produtos (nome, valor, estoque, marca) VALUES ('Camiseta preta base',  79.00, 1235, 4);
INSERT INTO produtos (nome, valor, estoque, marca) VALUES ('Bolsa Colcci Lisa',  249.00, 112, 3);
INSERT INTO produtos (nome, valor, estoque, marca) VALUES ('Camisa Adidas Originals',  346.00, 344, 2);
INSERT INTO produtos (nome, valor, estoque, marca) VALUES ('Tênis WM preto',  988.00, 2341, 6);
INSERT INTO produtos (nome, valor, estoque, marca) VALUES ('Bota Colcci azul',  1540.00, 143, 3);
INSERT INTO produtos (nome, valor, estoque, marca) VALUES ('Scarpin feminino salto',  877.00, 673, 7);
INSERT INTO produtos (nome, valor, estoque, marca) VALUES ('Camiseta Nike Dri-FIT',  124.00, 228, 1);
INSERT INTO produtos (nome, valor, estoque, marca) VALUES ('Camisa polo azul',  233.00, 549, 8);
INSERT INTO produtos (nome, valor, estoque, marca) VALUES ('Camisa Polo Tommy Hilfiger',  499.00, 794, 4);
INSERT INTO produtos (nome, valor, estoque, marca) VALUES ('Sandália Vizzano',  1540.00, 83, 7);
INSERT INTO produtos (nome, valor, estoque, marca) VALUES ('Tênis Adidas Superstar',  769.00, 326, 2);
INSERT INTO produtos (nome, valor, estoque, marca) VALUES ('Camiseta algodão verde',  76.99, 1214, 9);
INSERT INTO produtos (nome, valor, estoque, marca) VALUES ('Short Nike Nk',  298.00, 683, 1);
INSERT INTO produtos (nome, valor, estoque, marca) VALUES ('Camisa Aramis geométrica',  355.00, 1033, 8);
INSERT INTO produtos (nome, valor, estoque, marca) VALUES ('Bolsa Nike Unissex',  265.29, 596, 1);
INSERT INTO produtos (nome, valor, estoque, marca) VALUES ('Camiseta Aramis vermelha',  199.00, 457, 8);
INSERT INTO produtos (nome, valor, estoque, marca) VALUES ('Boné Tommy Jeans',  204.64, 68, 4);
INSERT INTO produtos (nome, valor, estoque, marca) VALUES ('Jaqueta Adidas ECO',  609.98, 116, 2);
SELECT * FROM produtos;


SELECT
	produtos.nome as Nome_Produto,
    marcas.nome as Marca_Protudo,
    produtos.valor as Valor_Protudo
FROM produtos 
INNER JOIN marcas ON (marcas.codigo = produtos.marca);


SELECT
	marcas.nome AS Nome_Marca,
    COUNT(*) AS Quantidade
FROM marcas INNER JOIN produtos ON (produtos.marca = marcas.codigo) GROUP BY marcas.nome;


SELECT
	produtos.nome as Nome_Produto,
    marcas.nome as Marca_Protudo,
    produtos.valor as Valor_Protudo
FROM produtos 
INNER JOIN marcas ON (marcas.codigo = produtos.marca) ORDER BY produtos.valor DESC;


SELECT
	AVG(produtos.valor) AS Média,
	marcas.nome AS Marca
FROM produtos INNER JOIN marcas ON (marcas.codigo = produtos.marca) GROUP BY marcas.nome;


SELECT
	produtos.nome AS Nome_Produto,
    produtos.valor AS Valor_Produto,
    marcas.nome AS Marca_Produto,
    produtos.estoque AS Quantidade_em_estoque
FROM produtos
INNER JOIN marcas ON (marcas.codigo = produtos.marca)
WHERE produtos.valor = (SELECT MAX(valor) FROM produtos);


SELECT 
	produtos.nome AS Nome_produto,
	produtos.valor AS Valor_protudo,
	produtos.estoque AS Quantidade_em_estoque,
	marcas.nome AS Marca_produto
FROM produtos 
INNER JOIN marcas ON (marcas.codigo = produtos.marca)
WHERE produtos.estoque BETWEEN 500 AND 1000;


SELECT 
	produtos.nome AS Produto,
    produtos.valor AS Valor,
    produtos.estoque AS Estoque
FROM produtos
WHERE produtos.nome LIKE '%Blusa%' OR produtos.nome LIKE '%Camiseta%' OR produtos.nome LIKE '%Camisa%'
ORDER BY produtos.valor DESC;


SELECT
	SUM(produtos.valor) AS Soma_do_produtos,
	marcas.nome AS Marca
FROM produtos
INNER JOIN marcas ON (marcas.codigo = produtos.marca)
GROUP BY marcas.nome;


SELECT
	marcas.nome
FROM marcas
INNER JOIN produtos ON (produtos.marca = marcas.codigo)
WHERE produtos.valor = (SELECT MAX(valor) FROM produtos);


SELECT
	produtos.nome,
    produtos.estoque
FROM produtos
WHERE produtos.estoque >= ( SELECT AVG(estoque) FROM produtos );


DROP TABLE produtos;
DROP TABLE marcas;
